# https://zhuanlan.zhihu.com/p/250534172
name: Auto Deploy
on:
  schedule:
    - cron: '0 10,22 * * *' # 北京时间上午和下午的的6点自动执行
    # every 12 hours: 0 */12 * * *
#   push:
#     branches:
#       - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  profile-readme:
    # https://github.com/marketplace/actions/profile-readme
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create README.md
        uses: actions-js/profile-readme@master
        with:
          username: zryyyy
          github_token: ${{ secrets.TOKEN }}
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.TOKEN }}
  profile-readme-development-stats:
    # https://github.com/marketplace/actions/profile-readme-development-stats
    needs: profile-readme
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Profile Readme Development Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.TOKEN }}
          # SHOW_PROFILE_VIEWS: "False"
          # SHOW_UPDATED_DATE: "False"
          # SHOW_LINES_OF_CODE: "False"
          # SHOW_OS: "False"
          # SHOW_PROJECTS: "False"
          # SHOW_LOC_CHART: "False"
          # SHOW_EDITORS: "True"
          # SHOW_TIMEZONE: "True"
          # SHOW_COMMIT: "True"
          # SHOW_LANGUAGE: "True"
          # SHOW_LANGUAGE_PER_REPO: "True"
          # SHOW_DAYS_OF_WEEK: "True"
          # SHOW_SHORT_INFO: "True"
          # LOCALE: en
          # COMMIT_BY_ME: "False"
          # COMMIT_MESSAGE: Updated with Dev Metrics
          # SHOW_TOTAL_CODE_TIME: "True"

#   profile_readme:
#     # https://github.com/marketplace/actions/profile-readme
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@master
#         with:
#           persist-credentials: false
#           fetch-depth: 0
#       - name: Create README.md
#         uses: actions-js/profile-readme@master
#         with:
#           username: zryyyy
#           github_token: ${{ secrets.TOKEN }}
#       - name: Commit & Push changes
#         uses: actions-js/push@master
#         with:
#           github_token: ${{ secrets.TOKEN }}
#   profile_stack:
#     # 因为奇怪的错误被弃用
#     # https://github.com/marketplace/actions/profile_stack
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: gleich/profile_stack@master
#         with:
#           path: stack.yml
#           badges: false
#           technology_emoji: 👨🏻‍💻
#           project_emoji: 🚀
#   profile-readme-development-stats:
#     # https://github.com/marketplace/actions/profile-readme-development-stats
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
