name: Test Deploy
on:
  # push:
  #   branches:
  #     - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# permissions: write-all

jobs:
  # profile-readme:
  #   # https://github.com/marketplace/actions/profile-readme
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@main
  #       with:
  #         persist-credentials: false
  #         fetch-depth: 0
  #     - name: Create README.md
  #       uses: actions-js/profile-readme@master
  #       with:
  #         username: ${{ github.actor }}
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #     - name: Commit & Push changes
  #       uses: actions-js/push@master
  #       with:
  #         author_name: github-actions[bot]
  #         author_email: 41898282+github-actions[bot]@users.noreply.github.com
  #         github_token: ${{ secrets.GITHUB_TOKEN }}

  profile-readme-development-stats:
    # https://github.com/marketplace/actions/profile-readme-development-stats
    # needs: profile-readme
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          fetch-depth: 0  # 确保获取完整的提交历史

      - name: Reset to last user commit
        shell: bash
        run: |
          # 找到最后一个不是由机器人提交的提交
          LAST_USER_COMMIT=$(git log --pretty=format:'%H %an' | grep -Ev 'readme-bot|github-actions\[bot\]' | head -n1 | awk '{print $1}')
          echo "Last user commit: $LAST_USER_COMMIT"
          # 重置到该提交
          git reset --hard $LAST_USER_COMMIT
          git push origin main --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Profile Readme Development Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.TOKEN }}
          SHOW_PROFILE_VIEWS: "False" # 项目浏览量（标签）
          SHOW_UPDATED_DATE: "False" # 最后一次更新的时间
          SHOW_LINES_OF_CODE: "False" # 代码行数（标签）
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
          SHOW_LOC_CHART: "False" # 在图表中区分不同年份
          SHOW_EDITORS: "True"
          SHOW_TIMEZONE: "True"
          SHOW_COMMIT: "True"
          SHOW_LANGUAGE: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_SHORT_INFO: "False" # 短个人信息
          LOCALE: "en"
          COMMIT_BY_ME: "False" # 用自己的邮箱提交
          COMMIT_MESSAGE: "Updated with Dev Metrics" # 提交摘要
          SHOW_TOTAL_CODE_TIME: "False" # 写代码总时间（标签）

  # 清除老的workflow
  delete-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 7  # 设置保留7天以内的workflow runs
          keep_minimum_runs: 3  # 每个workflow至少保留3次运行记录
  # https://github.com/strumwolf/delete-deployment-environment 删除 gh-pages
  # delete-deployment-environment:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Delete deployment
  #       uses: strumwolf/delete-deployment-environment@main
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         environment: github-pages
  #         onlyRemoveDeployments: true